In [1]:
%run initialize.py
import dataset as ds

Python version: 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
IPython version: 5.3.0
pandas version: 0.20.1 name: pd
NumPy version: 1.12.1 name: np
SciPy version: 0.19.0 name: sp
scikit-learn version: 0.18.1 name: skl
plotly version: 2.0.11 name: py
matplotlib version: 2.0.2 name: mpl


In [104]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

Load data files

In [8]:
parameters2 = ds.load_dataset('data/parameters_2.xlsx', filetype='xls', index_first_col=True)
demands2 = ds.load_dataset('data/demands_2.xlsx', filetype='xls', index_first_col=True)
ratings2 = ds.load_dataset('data/ratings_2.xlsx', filetype='xls', index_first_col=True)
parameters3 = ds.load_dataset('data/parameters_3.xlsx', filetype='xls', index_first_col=True)
demands3 = ds.load_dataset('data/demands_3.xlsx', filetype='xls', index_first_col=True)
ratings3 = ds.load_dataset('data/ratings_3.xlsx', filetype='xls', index_first_col=True)

Run clean_sequence to get data into usable format

In [9]:
demands2 = ds.clean_sequence(demands2)
ratings2 = ds.clean_sequence(ratings2)
demands3 = ds.clean_sequence(demands3)
ratings3 = ds.clean_sequence(ratings3)

Concatenate 2 and 3-span dataframes

In [17]:
parameters = pd.concat([parameters2,parameters3])
demands = pd.concat([demands2,demands3])
ratings = pd.concat([ratings2,ratings3])

Define indicies of zero ts and convert to zero indexing for Python.

In [31]:
idx = [115, 206, 219, 289, 320]
zero_idx = [x-1 for x in idx]

Get slg and fe shear demands (and locations) for zero_idx

In [41]:
slg_max_dl1v = demands['slg_max_dl1v'][zero_idx]
slg_max_dl2v = demands['slg_max_dl2v'][zero_idx]
slg_max_llv = demands['slg_max_llv'][zero_idx]
fe_max_dl1v = demands['fe_max_dl1v'][zero_idx]
fe_max_dl2v = demands['fe_max_dl2v'][zero_idx]
fe_max_llv = demands['fe_max_llv'][zero_idx]
slg_max_dl1v_loc = demands['slg_max_dl1v_loc'][zero_idx]
slg_max_dl2v_loc = demands['slg_max_dl2v_loc'][zero_idx]
slg_max_llv_loc = demands['slg_max_llv_loc'][zero_idx]
fe_max_dl1v_loc = demands['fe_max_dl1v_loc'][zero_idx]
fe_max_dl2v_loc = demands['fe_max_dl2v_loc'][zero_idx]
fe_max_llv_loc = demands['fe_max_llv_loc'][zero_idx]

Compare slg shear to fe shear for zero_idx samples

In [82]:
# exterior girder slg dead load shear
ext_slg_max_dlv = np.floor([slg_max_dl1v.values[x][1]+slg_max_dl2v.values[x][1] for x in range(0,5)])
ext_slg_max_dlv

array([ 104296.,   95222.,  118879.,   65314.,   71281.])

In [84]:
# exterior girder slg dead load shear
ext_fe_max_dlv = np.floor([np.max(fe_max_dl1v.values[x])+np.max(fe_max_dl2v.values[x]) for x in range(0,5)])
ext_fe_max_dlv

array([ 163337.,  139167.,  166424.,  108810.,  121204.])

In [90]:
# ratio of slg to fe dead load shear for zero_idx
ratio_ext_dlv = ext_slg_max_dlv/ext_fe_max_dlv
ratio_ext_dlv

array([ 0.6385326 ,  0.6842283 ,  0.71431404,  0.60025733,  0.58810765])

In [86]:
# exterior girder slg live load shear
ext_slg_max_llv = np.floor([slg_max_llv.values[x][1] for x in range(0,5)])
ext_slg_max_llv

array([ 115372.,  115257.,  133464.,  104671.,  106831.])

In [87]:
# exterior girder fe live load shear
ext_fe_max_llv = np.floor([np.max(fe_max_llv.values[x]) for x in range(0,5)])
ext_fe_max_llv

array([ 159580.,  117242.,  109325.,   88228.,   83373.])

In [89]:
# ratio of slg to fe live load shear for zero_idx
ratio_ext_llv = ext_slg_max_llv/ext_fe_max_llv
ratio_ext_llv

array([ 0.7229728 ,  0.98306921,  1.22080037,  1.18636941,  1.28136207])

How do they compare to the rest of the population?

In [92]:
slg_max_dl1v = demands['slg_max_dl1v']
slg_max_dl2v = demands['slg_max_dl2v']
slg_max_llv = demands['slg_max_llv']
fe_max_dl1v = demands['fe_max_dl1v']
fe_max_dl2v = demands['fe_max_dl2v']
fe_max_llv = demands['fe_max_llv']
slg_max_dl1v_loc = demands['slg_max_dl1v_loc']
slg_max_dl2v_loc = demands['slg_max_dl2v_loc']
slg_max_llv_loc = demands['slg_max_llv_loc']
fe_max_dl1v_loc = demands['fe_max_dl1v_loc']
fe_max_dl2v_loc = demands['fe_max_dl2v_loc']
fe_max_llv_loc = demands['fe_max_llv_loc']

In [101]:
ext_slg_max_dlv = np.floor([slg_max_dl1v.values[x][1]+slg_max_dl2v.values[x][1] for x in range(0,len(slg_max_dl1v))])
ext_fe_max_dlv = np.floor([fe_max_dl1v.values[x][1]+fe_max_dl2v.values[x][1] for x in range(0,len(slg_max_dl1v))])
ratio_ext_dlv = ext_slg_max_dlv/ext_fe_max_dlv

In [100]:
length = parameters['length'].values
spacing = parameters['gdr_spacing'].values
skew = parameters['skew'].values

In [136]:
tol = df = pd.read_excel('data/tol.xlsx')
tol.values
# t = np.squeeze(tol.values)
# t

array([[ 18.54225154],
       [  3.35462198],
       [ 25.33599814],
       [ 10.3362647 ],
       [  4.8021412 ],
       [  2.08623944],
       [  8.99075047],
       [ 10.17243653],
       [  0.6623605 ],
       [  8.38149574],
       [  1.21850166],
       [ 24.87247349],
       [ 14.27113837],
       [  4.09970844],
       [ 10.06381284],
       [  3.31056527],
       [  3.66549173],
       [ 21.04695864],
       [  7.39655616],
       [  9.46740911],
       [  4.55890706],
       [ 19.62133491],
       [  7.31706289],
       [  5.13168047],
       [  2.15032385],
       [  6.66981331],
       [  7.83100657],
       [ 25.93131508],
       [  3.60130406],
       [  7.23030679],
       [  5.38259364],
       [  7.14013727],
       [ 14.96798627],
       [ 13.00017483],
       [ 11.50269077],
       [  4.19700761],
       [  6.69388672],
       [  6.66692769],
       [  7.51231329],
       [  9.79221418],
       [  7.51889941],
       [ 10.94919373],
       [ 15.44884711],
       [  4

In [131]:
X = length
Y = t
# sz = ratio_ext_dlv

trace0 = py.graph_objs.Scatter(x = X, y = Y, mode = 'markers')
# trace0 = py.graph_objs.Scatter(x = X, y = Y, mode = 'markers', marker=dict(size=sz))
data = [trace0]
# layout = py.graph_objs.Layout(xaxis=dict(range=[0, 0.3]),yaxis=dict(range=[0, 25]))

fig = py.graph_objs.Figure(data=data)
iplot(fig) 